// Asserts what would actually ship in the .vsix.
//
// .vscodeignore is a denylist, and denylists rot. A new dev file lands in the
// repo, nobody adds a line, and it ships — which is exactly how
// tsconfig.base.json, knip.jsonc, eslint.config.ts and .github/ were all being
// packaged before this check existed. Nothing failed; the files were just
// quietly in the .vsix.
//
// The fix is not a better denylist. It is asking vsce itself which files it
// would package and asserting the answer against an explicit list, so the
// question "should this ship?" gets asked at the moment a file is added rather
// than the moment someone thinks to run `vsce ls`.
//
// Deliberately not used: the "files" field in package.json. While a
// .vscodeignore exists, vsce never reads it — collectFiles only consults
// manifest.files when the .vscodeignore read fails with ENOENT — and `vsce
// package` exits 1 outright if both are present. So a "files" allowlist here
// would be silently dead: `vsce ls` would ignore it and still print success.
//
// Requires a build first (media/preview.js is generated, media/vendor/ is
// copied), so this runs after `npm run build`, not as part of `npm run check`.
//
// Run: node scripts/package-check.ts
//
// `require` rather than `import` keeps this file CommonJS, which is what lets
// Node run it directly; the cast reattaches the module type @types/node widens
// to `any`. See esbuild.ts for the full note.
const fs = require('fs') as typeof import('fs');
const path = require('path') as typeof import('path');
const { listFiles } = require('@vscode/vsce') as typeof import('@vscode/vsce');

const root = path.join(__dirname, '..');

// Must be in the .vsix or the extension is broken for every user. The webview
// assets are the interesting half: they resolve against extensionUri inside the
// running extension, so a missing one is invisible in the dev host, where the
// same path is read straight off the repo checkout. It only breaks once
// packaged — which is why it is asserted here rather than eyeballed.
const REQUIRED = [
  'package.json', // "main", plus the contributes block
  'out/extension.js', // the extension host bundle
  'media/preview.js', // the webview bundle
  'media/preview.css', // the webview stylesheet
  'media/vendor/mermaid.min.js', // diagrams
  'media/vendor/katex/katex.min.css', // math, server-rendered to KaTeX HTML
  'media/vendor/katex/fonts/KaTeX_Main-Regular.woff2', // ...which needs its fonts
  'icon.png',
  'README.md',
  'CHANGELOG.md',
  'LICENSE',
];

// Everything that may ship, as a whole class. A file that is not matched by any
// of these fails the check, so adding runtime content means editing this list —
// a deliberate act, which is the point.
const ALLOWED = [
  // Root package metadata, the Marketplace listing assets, and the entry point.
  /^(package\.json|README\.md|CHANGELOG\.md|LICENSE|icon\.png)$/,
  // The extension host bundle. esbuild inlines every runtime dependency into it,
  // so node_modules never ships and neither does anything else in out/.
  /^out\/extension\.js$/,
  // The webview's own bundle and hand-written stylesheet.
  /^media\/(preview\.js|preview\.css)$/,
  // KaTeX CSS + fonts and mermaid.min.js, copied out of node_modules by
  // scripts/copy-assets.ts. The webview's CSP blocks a CDN, so these must ship.
  /^media\/vendor\//,
  // Screenshots the README embeds; the Marketplace renders them out of the .vsix.
  /^images\//,
];

async function main(): Promise<void> {
  const files = (await listFiles({ cwd: root })).map((f) => f.split(path.sep).join('/'));
  const shipped = new Set(files);

  let failures = 0;
  const check = (name: string, cond: boolean, detail?: string): void => {
    console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}`);
    if (!cond) {
      failures++;
      if (detail) console.log(`      ${detail}`);
    }
  };

  console.log(`${files.length} file(s) would be packaged.\n`);

  for (const required of REQUIRED) {
    check(
      `ships ${required}`,
      shipped.has(required),
      'excluded by .vscodeignore, or not built — media/ is generated by `npm run build`'
    );
  }

  // The dev-only timing instrumentation must not reach a user. esbuild strips it
  // by substituting `__PROFILE__`, and the minifier then drops the bodies — but
  // "the minifier should have removed it" is a belief about a tool, and this is
  // a fact about the artifact. The literal below is perf.ts's report header; if
  // it is in the bundle, the bundle is instrumented.
  //
  // Both a `--profile` build and an unminified `--watch` build carry it, which
  // is why the failure names the fix rather than just reporting a defect. A real
  // release is never in this state: `vsce package` runs `vscode:prepublish`,
  // which is `npm run build`.
  for (const bundle of ['media/preview.js', 'out/extension.js']) {
    const abs = path.join(root, bundle);
    const instrumented = fs.existsSync(abs) && fs.readFileSync(abs, 'utf8').includes('graphite.md profile]');
    check(
      `${bundle} ships without profiling instrumentation`,
      !instrumented,
      `run \`npm run build\` — this tree was built with --profile or in watch mode`
    );
  }

  const unexpected = files.filter((f) => !ALLOWED.some((p) => p.test(f))).sort();
  check(
    `no unexpected files (${unexpected.length})`,
    unexpected.length === 0,
    unexpected.length > 0
      ? `add to .vscodeignore if dev-only, or to ALLOWED in scripts/package-check.ts if it is runtime content:\n      ${unexpected.join('\n      ')}`
      : ''
  );

  console.log(failures === 0 ? '\nPackaging check passed.' : `\n${failures} check(s) FAILED.`);
  process.exitCode = failures === 0 ? 0 : 1;
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
